FROM golang:1.24-alpine AS builder
WORKDIR /app
RUN apk --no-cache add gcc musl-dev sqlite-dev
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 go build -o pathfinder-api .

FROM alpine:latest
RUN apk --no-cache add ca-certificates sqlite-libs
WORKDIR /root/
COPY --from=builder /app/pathfinder-api .
COPY config.toml .
EXPOSE 8080
CMD ["./pathfinder-api"]
